name: mn_qr_scanner
description: "A QR code scanner that sends data to a saved URL."
publish_to: 'none' 

# Version & build number
version: 1.0.0+1

# SDK compatibility
environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  
  shared_preferences: ^2.2.1 
  qr_code_scanner: ^1.0.0 


# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3  

# Flutter settings
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

application:
    label: "MN QR Scanner"

  # App icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  
